version: "3.9"
services:
  web:
    build: ./chronos
    ports:
      - "3000:3000"
    networks:
      - service
  back-end:
    build: ./prometheus
    ports:
      - "5000:5000"
    networks:
      - service
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: entropy
      POSTGRES_PASSWORD: entropy123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    ports:
      - "5432:5432"
    networks:
      - service

networks:
  service:
