version: "3.9"
services:
  web:
    build: ./chronos
    ports:
      - "3000:3000"
    networks:
      - service
  back-end:
    build: ./prometheus
    ports:
      - "5000:5000"
    networks:
      - service
networks:
  service:
